version: '3.9'

services:
  api:
    container_name: motors_shop_api
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
      - DB_USER=luish
      - DB_PASSWORD=1234
      - DB=motors_shop_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    container_name: motors_shop_database
    image: postgres:14
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=luish
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=motors_shop_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U luish -d motors_shop_db"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 5s
    volumes:
      - postgres_motors_shop:/var/lib/postgresql/data

volumes:
  postgres_motors_shop:
    driver: local
